version: '3.3'

services:
  web:
    image: naja-modals-test-project_web
    build: .docker/apache
    volumes:
      - ./:/var/www/html
      - ./.docker/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./.docker/cache:/cache
    ports:
      - '80:80'

  console:
    image: ghcr.io/webnazakazku/docker-php-build:7.3
    entrypoint: /tmp/entrypoint.sh
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.docker/cache:/cache
      - ./.docker/console/root:/root
      - ./.docker/console/.bashrc:/tmp/.bashrc
      - ./.docker/console/entrypoint.sh:/tmp/entrypoint.sh
